In [1]:
import pandas as pd
import numpy as np
import torch

BATCH_SIZE = 16
NUM_CONTEXT = 3

In [10]:
train_data_prepped_all_segments = pd.read_pickle("prepped.pkl")

In [12]:
train_data_prepped_all_segments["date"].max() # needs fixing

Timestamp('2014-12-18 00:00:00')

In [4]:
dfs = []
items_per_batch = (NUM_CONTEXT + 1) * BATCH_SIZE
for i, group in train_data_prepped_all_segments.groupby(["ticker", "seq_len"]):
    num_rows = (len(group) // items_per_batch) * items_per_batch
    if not num_rows:
        next
    # print(num_rows)
    # print(len(group))
    dfs.append(group.sample(frac=1)[:num_rows])
    # print(group.sample(frac=1)[:num_rows]["seq_len"])
df = pd.concat(dfs).reset_index()

In [5]:
len(df)/len(train_data_prepped_all_segments)

0.6541102252073415

In [13]:
shuffled = (
    df
    .assign(group_var=df.index // items_per_batch)
    .set_index("group_var")
    .loc[np.random.permutation(len(df) // items_per_batch)]
)

In [14]:
shuffled.reset_index()["group_var"].head(66)

0      619
1      619
2      619
3      619
4      619
      ... 
61     619
62     619
63     619
64    2558
65    2558
Name: group_var, Length: 66, dtype: int64

In [19]:
for start in range(0, len(shuffled), items_per_batch):
    batch = shuffled.iloc[start : start + items_per_batch]
    seq_len = batch["seq_len"].iloc[0]
    x = torch.reshape(
        torch.cat(batch["x"].tolist()).unsqueeze(0),
        [NUM_CONTEXT + 1, BATCH_SIZE, seq_len, 1],
    ).permute(1, 2, 3, 0)

    x_context = x[:,:,:,:NUM_CONTEXT]
    x_test = x[:,:,:,-1:]

    y = torch.reshape(
        torch.cat(batch["y"].tolist()).unsqueeze(0),
        [NUM_CONTEXT + 1, BATCH_SIZE, seq_len, 1],
    ).permute(1, 2, 3, 0)

    y_context = y[:,:,:,:NUM_CONTEXT]
    y_test = y[:,:,:,-1:]

    # if batch["x"].iloc[0].shape[1] == 3:
    #     break


In [18]:
y[:,:,:,-1:]

tensor([[[[ 5.5173e-01]],

         [[ 6.6460e-01]],

         [[-1.4362e-01]]],


        [[[-5.7611e-02]],

         [[ 4.4183e-01]],

         [[-1.9736e+00]]],


        [[[ 7.0707e-01]],

         [[-2.1123e-01]],

         [[-2.1502e+00]]],


        [[[ 1.5707e+00]],

         [[-2.5435e-01]],

         [[ 1.0955e+00]]],


        [[[ 2.1049e+00]],

         [[ 1.6921e+00]],

         [[-1.4110e+01]]],


        [[[ 1.4602e-01]],

         [[-3.5407e-01]],

         [[ 1.0452e-01]]],


        [[[ 9.5509e-01]],

         [[ 1.0029e+00]],

         [[-5.0016e-01]]],


        [[[ 6.5150e-01]],

         [[-1.0411e+00]],

         [[-2.3349e-02]]],


        [[[ 6.8894e-01]],

         [[-1.2934e+00]],

         [[ 1.2797e-01]]],


        [[[-4.8494e-01]],

         [[ 1.2925e+00]],

         [[-7.5936e-01]]],


        [[[ 1.9108e+00]],

         [[ 8.5546e-02]],

         [[-3.7044e-01]]],


        [[[-7.9234e-01]],

         [[ 1.1913e+00]],

         [[ 6.2891e-01]]],


    

In [95]:
new.unsqueeze(0)

tensor([[[[ 2.0452],
          [ 0.6837],
          [ 2.6332]],

         [[-0.1186],
          [ 1.3793],
          [-0.5174]],

         [[ 0.6619],
          [-1.3322],
          [-0.4679]],

         [[-1.4070],
          [ 0.5727],
          [-0.6635]],

         [[ 0.3532],
          [ 1.8880],
          [ 2.2311]],

         [[ 0.5213],
          [ 0.0000],
          [-1.4115]],

         [[-0.7065],
          [ 0.2596],
          [ 1.2931]],

         [[ 1.4185],
          [-0.5459],
          [ 0.1109]],

         [[ 1.6386],
          [ 1.6837],
          [-0.0705]],

         [[ 1.7407],
          [-0.0659],
          [ 0.0943]],

         [[-0.8038],
          [ 0.9918],
          [-0.6688]],

         [[-0.6414],
          [-1.9613],
          [ 0.0000]],

         [[ 0.7250],
          [-0.1776],
          [ 1.8193]],

         [[ 0.0632],
          [ 0.2333],
          [-1.5775]],

         [[-0.6017],
          [ 1.1252],
          [-0.6119]],

         [[ 1.1336],
    

In [96]:
torch.reshape(new.unsqueeze(0), [4,16,3,1])

tensor([[[[ 2.0452],
          [ 0.6837],
          [ 2.6332]],

         [[-0.1186],
          [ 1.3793],
          [-0.5174]],

         [[ 0.6619],
          [-1.3322],
          [-0.4679]],

         [[-1.4070],
          [ 0.5727],
          [-0.6635]],

         [[ 0.3532],
          [ 1.8880],
          [ 2.2311]],

         [[ 0.5213],
          [ 0.0000],
          [-1.4115]],

         [[-0.7065],
          [ 0.2596],
          [ 1.2931]],

         [[ 1.4185],
          [-0.5459],
          [ 0.1109]],

         [[ 1.6386],
          [ 1.6837],
          [-0.0705]],

         [[ 1.7407],
          [-0.0659],
          [ 0.0943]],

         [[-0.8038],
          [ 0.9918],
          [-0.6688]],

         [[-0.6414],
          [-1.9613],
          [ 0.0000]],

         [[ 0.7250],
          [-0.1776],
          [ 1.8193]],

         [[ 0.0632],
          [ 0.2333],
          [-1.5775]],

         [[-0.6017],
          [ 1.1252],
          [-0.6119]],

         [[ 1.1336],
    

In [97]:
new.shape

torch.Size([64, 3, 1])

In [98]:
torch.reshape(new.unsqueeze(0), [4, 16, 3, 1]).shape

torch.Size([4, 16, 3, 1])

In [100]:
torch.reshape(new.unsqueeze(0), [4, 16, 3, 1]).permute(1,2,3,0)

tensor([[[[ 2.0452, -0.9720, -2.1521, -0.3089]],

         [[ 0.6837, -0.8153, -1.8281,  1.1618]],

         [[ 2.6332,  0.8331, -3.6993, -0.7473]]],


        [[[-0.1186,  0.1456, -0.5273, -1.1287]],

         [[ 1.3793, -1.1588, -1.4546,  0.6941]],

         [[-0.5174,  0.8064,  0.5437,  0.4955]]],


        [[[ 0.6619, -1.3009, -1.1843,  0.6975]],

         [[-1.3322,  0.6812,  0.7659,  0.3582]],

         [[-0.4679, -0.5415, -0.5934, -1.1791]]],


        [[[-1.4070,  1.3662, -0.0830, -0.4728]],

         [[ 0.5727,  2.0641, -2.0828, -0.2560]],

         [[-0.6635,  3.3383, -1.0597,  1.3574]]],


        [[[ 0.3532, -0.9992,  1.1119, -1.2580]],

         [[ 1.8880,  0.6939, -0.6998,  0.4963]],

         [[ 2.2311,  0.7693,  0.9397,  0.4510]]],


        [[[ 0.5213,  1.9486,  0.1180,  0.8700]],

         [[ 0.0000,  0.1373,  1.2954, -0.8056]],

         [[-1.4115,  0.3086, -0.6934,  0.9780]]],


        [[[-0.7065,  1.9757, -1.4037, -0.8379]],

         [[ 0.2596,  0.0618,  0.3779, 